[package]
name = "embedded_graphics_components"
version = "0.1.0"
edition = "2024"


[dependencies]
embedded-graphics = "0.8.1"


[dev-dependencies]
anyhow = "1.0.99"
embedded-graphics-simulator = "0.7.0"
